# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            reachtarunhere
tagline:          'My Blog'
description:      'I am Junior at BITS double majoring in Biological Sciences & Electronics-Instrumentation .'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Tarun Kumar Vangani'
  url:            https://reachtarunhere.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
