# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Stanley
tagline:          'Too many interests, too little time!'
description:      "Tarun Vangani's Blog"
url:              https://reachtarunhere.github.io
baseurl:          /

author:
  name:           'Tarun Kumar Vangani'
  url:            http://www.bits-pilani.ac.in/spp/f2013817

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/reachtarunhere/reachtarunhere.github.io

gems:
  - jekyll-seo-tag
